# Generated by Django 4.2.7 on 2023-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('acronimo', models.CharField(max_length=10)),
                ('otra_condicion', models.CharField(max_length=100)),
                ('arrendamiento', models.CharField(max_length=100)),
                ('horario_trabajo', models.CharField(max_length=100)),
                ('nomina', models.IntegerField()),
                ('voluntarios', models.IntegerField()),
                ('registrada', models.CharField(max_length=100)),
                ('calle_numero', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('delegacion', models.CharField(max_length=100)),
                ('cp', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('facebook_twitter', models.CharField(max_length=100)),
                ('sitioweb', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=500)),
                ('sector_marginado', models.CharField(max_length=500)),
                ('trayectoria', models.CharField(max_length=500)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono_responsable', models.IntegerField()),
                ('horario_atencion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
